---
title: "word_test"
author: "前田　和寛"
output:
  word_document:
    reference: set_APAlike.docx
bibliography: cit.bibtex
csl: apa.csl
abstract: オラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラオラ
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 走れ社畜(ネタです)

　社畜は激怒した。必ず、かの邪智暴虐のブラック組織を除かなければならぬと決意した。社畜には政治がわからぬ。社畜は、村の牧人である。笛を吹き、羊と遊んで暮して来た。けれども邪悪に対しては、人一倍に敏感であった。きょう未明社畜は村を出発し、野を越え山越え、十里はなれた此このシラクスの市にやって来た。社畜には父も、母も無い。女房も無い。十六の、内気な妹と二人暮しだ。この妹は、村の或る律気な一牧人を、近々、花婿として迎える事になっていた。結婚式も間近かなのである。社畜は、それゆえ、花嫁の衣裳やら祝宴の御馳走やらを買いに、はるばる市にやって来たのだ。先ず、その品々を買い集め、それから都の大路をぶらぶら歩いた。社畜には竹馬の友があった。社畜である。今は此のシラクスの市で、石工をしている。その友を、これから訪ねてみるつもりなのだ。久しく逢わなかったのだから、訪ねて行くのが楽しみである。歩いているうちに社畜は、まちの様子を怪しく思った。ひっそりしている。もう既に日も落ちて、まちの暗いのは当りまえだが、けれども、なんだか、夜のせいばかりでは無く、市全体が、やけに寂しい。のんきな社畜も、だんだん不安になって来た。路で逢った若い衆をつかまえて、何かあったのか、二年まえに此の市に来たときは、夜でも皆が歌をうたって、まちは賑やかであった筈はずだが、と質問した。若い衆は、首を振って答えなかった。しばらく歩いて老爺に逢い、こんどはもっと、語勢を強くして質問した。老爺は答えなかった。社畜は両手で老爺のからだをゆすぶって質問を重ねた。老爺は、あたりをはばかる低声で、わずか答えた。

「ブラック組織は、人を殺します。」  
「なぜ殺すのだ。」  
「余裕を抱いている、というのですが、誰もそんな、余裕を持っては居りませぬ。」  
「たくさんの人を殺したのか。」  
「はい、はじめは社畜さまを。それから、社畜さまを。それから、社畜さまを。それから、社畜さまを。それから、社畜さまを。それから、賢臣の社畜様を。」  
「おどろいた。残業は乱心か。」  
「いいえ、乱心ではございませぬ。納期を、信ずる事が出来ぬ、というのです。このごろは、臣下の心をも、お疑いになり、少しく派手な暮しをしている者には、休日いちにち差し出すことを命じて居ります。御命令を拒めばデスマーチにかけられて、殺されます。きょうは、六人殺されました。」

　聞いて、社畜は激怒した。「呆あきれたブラック組織だ。生かして置けぬ。」

## ビール飲みたいです

引用テスト。[@zousan]は時代遅れでしょう。時代はRStanですね。

## 引用文献
